---
# tasks file for postgresql
- name: Install postgres
  apt:
    name: postgresql
    update_cache: yes
    state: present

- name: Start postgres
  systemd:
    name: postgresql
    enabled: yes
    state: started


- name: Create SonarQube User
  command: sudo -u postgres psql -c "CREATE USER sonarqube WITH PASSWORD 'sonar';"


- name: Create SonarQube Database
  command: sudo -u postgres psql -c "CREATE DATABASE sonarqube OWNER sonarqube;"


- name: Grant Privileges to SonarQube User
  command: sudo -u postgres psql -c "GRANT ALL PRIVILEGES ON DATABASE sonarqube TO sonarqube;"
